export const email = 'buzon.tombuzon@gmail.com';
export const services = [
  { id: 'cadrage', title: 'Conseil & architecture', lead: 'Décider quoi construire, avant de le construire.', audience: 'Une idée à clarifier, un produit à débloquer ou un choix technique à trancher.',
    work: 'Audit de l’existant, entretiens sur les usages, comparaison des options et identification des dépendances. Un périmètre priorisé pour distinguer l’indispensable de la suite.',
    deliverables: ['Diagnostic et risques', 'Scénarios techniques argumentés', 'Feuille de route et critères de validation'],
    kpi: 'Décisions en suspens levées, risques testés, périmètre estimable.',
    limit: 'Le cadrage définit le budget et le calendrier ; il ne les suppose pas.', tags: ['Audit', 'Architecture', 'Roadmap'] },
  { id: 'mvp', title: 'Prototype & MVP', lead: 'Mettre une hypothèse entre les mains des utilisateurs.', audience: 'Un nouveau service à tester avant d’investir dans une application complète.',
    work: 'Parcours utilisateur, prototype fonctionnel, implémentation du scénario essentiel puis retours terrain. Le prototype teste la faisabilité ; le MVP teste un usage réel.',
    deliverables: ['Parcours et prototype utilisable', 'Code source et déploiement de démonstration', 'Plan de test et bilan des retours'],
    kpi: 'Taux de complétion du parcours, temps jusqu’à la première valeur, retours utilisateurs.',
    limit: 'Les fonctions secondaires restent dans une feuille de route explicite.', tags: ['UX', 'POC', 'Validation'] },
  { id: 'produit', title: 'Applications & plateformes', lead: 'Faire tenir toute l’expérience, du premier écran à la base de données.', audience: 'Un outil métier, un produit web, une application mobile ou desktop à concevoir ou reprendre.',
    work: 'Interfaces, API, authentification, données et intégrations. Accessibilité, performance et référencement technique sont intégrés au travail sur le web, avec une livraison documentée.',
    deliverables: ['Application front et back', 'Tests des parcours critiques', 'Documentation, déploiement et passation'],
    kpi: 'Erreurs par parcours, latence p95, Core Web Vitals, disponibilité selon l’hébergement.',
    limit: 'Hébergement, maintenance et services tiers sont cadrés séparément.', tags: ['Web', 'Mobile', 'Desktop'] },
  { id: 'ia', title: 'IA & assistants documentaires', lead: 'Relier un modèle à vos usages, vos sources et vos outils.', audience: 'Des documents difficiles à exploiter ou une interaction qui mérite un assistant contextualisé.',
    work: 'Préparation des sources, recherche documentaire RAG, choix du modèle, outils métier et interface de conversation. Évaluation sur des questions représentatives, y compris les cas où le modèle doit s’abstenir.',
    deliverables: ['Assistant intégré et sources reliées', 'Jeu de questions d’évaluation', 'Suivi de la latence, des erreurs et des coûts'],
    kpi: 'Réponses soutenues par les sources, taux d’abstention pertinent, coût par requête.',
    limit: 'Local ou cloud selon vos contraintes. Un assistant ne garantit pas une réponse juste à chaque question.', tags: ['RAG', 'LLM', 'Agents'] },
  { id: 'data', title: 'Data & machine learning', lead: 'Passer d’un jeu de données à une décision vérifiable.', audience: 'Un besoin de prédiction, de classification, de recherche ou de visualisation.',
    work: 'Audit et préparation des données, baseline, expérimentation puis évaluation sur un jeu distinct. Mise à disposition du résultat dans une API ou un tableau de bord.',
    deliverables: ['Pipeline de données reproductible', 'Modèle et rapport d’évaluation', 'API ou visualisation exploitable'],
    kpi: 'MAE pour une régression, précision/rappel pour une classification, dérive des données.',
    limit: 'La qualité et la disponibilité des données conditionnent les résultats.', tags: ['Python', 'ML', 'MLOps'] },
  { id: 'automation', title: 'Automatisation & intégrations', lead: 'Enlever les manipulations qui coupent vos journées.', audience: 'Des outils isolés, des ressaisies ou des tâches répétitives.',
    work: 'Cartographie du processus, connexion des API et automatisation des étapes stables. Gestion des erreurs, journalisation et reprise manuelle quand une exception survient.',
    deliverables: ['Workflow connecté à vos outils', 'Alertes et gestion des échecs', 'Documentation et reprise en main'],
    kpi: 'Temps par opération, taux d’échec, reprises manuelles et coût d’exécution.',
    limit: 'Les accès, quotas et possibilités des API tierces sont vérifiés au cadrage.', tags: ['API', 'Workflows', 'n8n'] },
  { id: 'creative', title: 'Expériences & prototypes créatifs', lead: 'Quand l’idée sort du navigateur.', audience: 'Une expérience qui mêle image, son, espace ou objet physique.',
    work: 'Modélisation et rendu 3D, pipelines vidéo et audio, interactions Godot ou prototype connecté. L’expérimentation commence par une preuve technique ciblée.',
    deliverables: ['Démonstrateur interactif ou média', 'Assets et sources convenus', 'Limites et recommandations pour la suite'],
    kpi: 'Fluidité, temps de rendu, synchronisation audiovisuelle ou latence d’interaction.',
    limit: 'Un prototype IoT n’est pas un produit industrialisé ou certifié.', tags: ['3D', 'Audio / vidéo', 'IoT'] },
];
export const archives = [
 ['Chess Agent', 'IA', 'Un coach d’échecs qui relie conversation et outils spécialisés.', 'LangGraph · Angular', 'Projet présenté dans le portfolio précédent.'],
 ['ML Delivery', 'Data', 'Rendre un modèle utilisable au-delà du notebook : suivi des expériences, API et orchestration.', 'MLflow · FastAPI · Airflow', 'Travail sur la chaîne de livraison ML.'],
 ['UseYourFridge', 'Applications', 'Relier les ingrédients disponibles, les recettes et la liste de courses dans une application mobile.', 'Angular · Ionic · TypeScript', 'Projet historique.'],
 ['Estimation immobilière', 'Data', 'Explorer des données immobilières publiques françaises et les restituer en visualisations.', 'JavaScript · CSV · Highcharts', 'Projet historique ; aucune précision prédictive revendiquée.'],
 ['Mosaic Generator', 'Création', 'Recomposer une image à partir d’une bibliothèque locale de petites images.', 'Python · Traitement d’image', 'Exploration créative.'],
 ['Teach Me Anything', 'Création', 'Assembler voix, texte et vidéo pour produire de courts contenus pédagogiques.', 'Python · n8n · JavaScript', 'Prototype historique.'],
 ['CryptoWatch', 'Applications', 'Porter une interface de suivi crypto au poignet.', 'Java · Kotlin · Galaxy Watch', 'Projet historique ; aucun conseil financier.'],
 ['TradeBroFamily', 'Applications', 'Expérimenter une interface autour de données et graphiques de marché.', 'JavaScript · TradingView', 'Projet historique ; aucun résultat de trading revendiqué.'],
 ['RAG local & fine-tuning', 'IA', 'Comparer recherche documentaire locale et adaptation de modèles selon les données et les contraintes.', 'LangChain · FAISS · Ollama', 'Expérimentations techniques.'],
 ['Vision & apprentissage', 'Data', 'Explorer la classification textile, la vision semi-supervisée et l’apprentissage par renforcement.', 'Python · VGG16 · LunarLander', 'Travaux d’apprentissage et prototypes.'],
 ['Recommandation & outils de tâches', 'IA', 'Premières explorations de recommandation e-commerce et d’assistance à la gestion de tâches.', 'TensorFlow · React · Node', 'Archives du premier site ; statut de livraison non confirmé.'],
];
